name: Fadairo
favicon: null
layout_spectrum: 0.853137485915795
typography_spectrum: 0.3209080307278782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.18231505318544805
  lightness: 0.4768811473622918
  saturation: 0.8538675559684634
  rhythmicContrast: 0.8369290705304593
purpose: []
